# Generated by Django 2.1.7 on 2019-02-16 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Location', models.CharField(max_length=45)),
                ('Details', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AUIN', models.IntegerField()),
                ('FirstName', models.CharField(max_length=45)),
                ('LastName', models.CharField(max_length=45)),
                ('MiddleName', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('Name', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('ActivitiesPerSemester', models.IntegerField()),
                ('AdvisingPerSemester', models.FloatField()),
                ('Activities', models.ManyToManyField(to='eh_app.Activity')),
                ('Advisors', models.ManyToManyField(to='eh_app.Advisor')),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=15)),
                ('Description', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Semester', models.CharField(max_length=16)),
                ('AcademicYear', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('UIN', models.IntegerField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=45)),
                ('LastName', models.CharField(max_length=45)),
                ('MiddleName', models.CharField(max_length=45)),
                ('Email', models.EmailField(max_length=45)),
                ('GPA', models.FloatField()),
                ('TimesOnProbation', models.IntegerField(default=0)),
                ('TimesDismissed', models.IntegerField(default=0)),
                ('Majors', models.CharField(max_length=45)),
                ('RequirementException', models.IntegerField(choices=[(0, '0'), (1, 'Admitted The After 12th Day'), (2, 'Co-Op'), (3, 'Galveston Campus'), (4, 'Internship'), (5, 'ECOS Coach'), (6, 'ECOS Fellow'), (7, 'Ambassador'), (8, 'Excom'), (9, 'Family Leave'), (10, 'Medical Leave'), (11, 'Taking The Semester Off'), (12, 'Not in Ecampus and Cohort'), (13, 'Missionary Work'), (14, 'Study Abroad'), (15, 'Not in EH'), (16, 'Unknown'), (17, 'Withdrew')])),
                ('Graduated', models.BooleanField(default=False)),
                ('ActivitiesAttended', models.ManyToManyField(to='eh_app.Activity')),
                ('Departments', models.ForeignKey(on_delete=None, to='eh_app.Department')),
                ('GraduationSemester', models.ForeignKey(on_delete=None, related_name='semester_graduated', to='eh_app.Semester')),
                ('SemesterStart', models.ForeignKey(on_delete=None, to='eh_app.Semester')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=45)),
                ('SemesterStarted', models.ForeignKey(on_delete=None, to='eh_app.Semester')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='Track',
            field=models.ForeignKey(on_delete=None, to='eh_app.Track'),
        ),
        migrations.AddField(
            model_name='advisor',
            name='Track',
            field=models.ForeignKey(on_delete=None, to='eh_app.Track'),
        ),
        migrations.AddField(
            model_name='activity',
            name='RequirementSatisfied',
            field=models.ForeignKey(on_delete=None, to='eh_app.Requirement'),
        ),
        migrations.AddField(
            model_name='activity',
            name='Semester',
            field=models.ForeignKey(on_delete=None, to='eh_app.Semester'),
        ),
    ]
