# Generated by Django 2.1.7 on 2019-02-17 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Location', models.CharField(max_length=45)),
                ('Details', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('UIN', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=45)),
                ('LastName', models.CharField(max_length=45)),
                ('MiddleName', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('Number', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('Title', models.CharField(default=None, max_length=45)),
                ('Credits', models.PositiveIntegerField(default=None)),
                ('MinCredits', models.PositiveIntegerField(default=None)),
                ('MaxCredits', models.PositiveIntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('Name', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('ActivitiesPerSemester', models.PositiveIntegerField()),
                ('AdvisingPerSemester', models.FloatField()),
                ('Activities', models.ManyToManyField(to='eh_app.Activity')),
                ('Advisors', models.ManyToManyField(to='eh_app.Advisor')),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=15)),
                ('Description', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('CRN', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('Number', models.PositiveIntegerField()),
                ('Level', models.CharField(choices=[('L', 'Lower'), ('U', 'Upper')], default=None, max_length=1)),
                ('Campus', models.ForeignKey(default=None, on_delete=None, to='eh_app.Campus')),
                ('Course', models.ForeignKey(default=None, on_delete=None, to='eh_app.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Semester', models.CharField(max_length=16)),
                ('AcademicYear', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('UIN', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=45)),
                ('LastName', models.CharField(max_length=45)),
                ('MiddleName', models.CharField(max_length=45)),
                ('Email', models.EmailField(max_length=45)),
                ('GPA', models.FloatField()),
                ('TimesOnProbation', models.PositiveIntegerField(default=0)),
                ('TimesDismissed', models.PositiveIntegerField(default=0)),
                ('Majors', models.CharField(max_length=45)),
                ('Graduated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('UIN', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=45)),
                ('LastName', models.CharField(max_length=45)),
                ('MiddleName', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=45)),
                ('SemesterStarted', models.ForeignKey(on_delete=None, to='eh_app.Semester')),
            ],
        ),
        migrations.CreateModel(
            name='Exception',
            fields=[
                ('TypeOfLeave', models.CharField(max_length=45, unique=True)),
                ('LeaveDuration', models.CharField(default=None, max_length=10)),
                ('Student', models.OneToOneField(on_delete=None, primary_key=True, serialize=False, to='eh_app.Student')),
                ('Semester', models.ForeignKey(on_delete=None, to='eh_app.Semester')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='ActivitiesAttended',
            field=models.ManyToManyField(to='eh_app.Activity'),
        ),
        migrations.AddField(
            model_name='student',
            name='Departments',
            field=models.ForeignKey(on_delete=None, to='eh_app.Department'),
        ),
        migrations.AddField(
            model_name='student',
            name='SemesterGraduation',
            field=models.ForeignKey(on_delete=None, related_name='semester_graduation', to='eh_app.Semester'),
        ),
        migrations.AddField(
            model_name='student',
            name='SemesterStart',
            field=models.ForeignKey(on_delete=None, to='eh_app.Semester'),
        ),
        migrations.AddField(
            model_name='section',
            name='Semester',
            field=models.ForeignKey(on_delete=None, to='eh_app.Semester'),
        ),
        migrations.AddField(
            model_name='section',
            name='Teacher',
            field=models.ForeignKey(default=None, on_delete=None, to='eh_app.Teacher'),
        ),
        migrations.AddField(
            model_name='department',
            name='Track',
            field=models.ForeignKey(on_delete=None, to='eh_app.Track'),
        ),
        migrations.AddField(
            model_name='course',
            name='Department',
            field=models.ForeignKey(on_delete=None, to='eh_app.Department'),
        ),
        migrations.AddField(
            model_name='advisor',
            name='Track',
            field=models.ForeignKey(on_delete=None, to='eh_app.Track'),
        ),
        migrations.AddField(
            model_name='activity',
            name='RequirementSatisfied',
            field=models.ForeignKey(on_delete=None, to='eh_app.Requirement'),
        ),
        migrations.AddField(
            model_name='activity',
            name='Semester',
            field=models.ForeignKey(on_delete=None, to='eh_app.Semester'),
        ),
        migrations.AddField(
            model_name='student',
            name='RequirementException',
            field=models.ForeignKey(on_delete=None, to='eh_app.Exception'),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('CRN', 'Semester')},
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('Number', 'Title')},
        ),
        migrations.AlterUniqueTogether(
            name='activity',
            unique_together={('id', 'RequirementSatisfied', 'Semester')},
        ),
        migrations.AlterUniqueTogether(
            name='exception',
            unique_together={('Semester', 'Student')},
        ),
    ]
